apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
nodeRegistration:
  criSocket: "unix:///var/run/containerd/containerd.sock"
  kubeletExtraArgs:
    - name: node-ip
      value: "10.0.0.10"
localAPIEndpoint:
  advertiseAddress: 10.0.0.10
  bindPort: 6443 
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
certificatesDir: "/etc/kubernetes/pki"
networking:
  podSubnet: "192.168.0.0/16"
  dnsDomain: "cluster.local"
  serviceSubnet: "10.96.0.0/16"
apiServer:
  extraArgs:
    - name: authorization-mode
      value: "Node,RBAC"
  certSANs:
  - "10.0.0.10"
  - "m1.home.lab"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
serverTLSBootstrap: true
tlsCipherSuites: [TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256]
resolvConf: "/run/systemd/resolve/resolv.conf"
