---
- hosts: master,workers
  gather_facts: no
  become: yes
  tasks:
  - name: containerd dir
    ansible.builtin.file:
      path: /etc/containerd
      state: directory
  - name: copy k8s sysctl
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      force: false
    loop:
      - src: containerd_config.toml
        dest: /etc/containerd/config.toml
      - src: k8s_module_load.conf
        dest: /etc/modules-load.d/k8s.conf
      - src: k8s_sysctl.conf
        dest: /etc/sysctl.d/50-k8s.conf
      - src: apt-key.gpg
        dest: /etc/apt/trusted.gpg.d/google-apt.gpg
  - name: modprobe
    community.general.modprobe:
      name: "{{ item }}"
      state: present
    with_items:
      - overlay
      - br_netfilter
      - rbd
  - name: sysctl
    sysctl:
      name: "{{ item }}"
      value: '1'
      state: present
    with_items:
      - net.bridge.bridge-nf-call-ip6tables
      - net.bridge.bridge-nf-call-iptables
      - net.ipv4.ip_forward
  - name: swap off
    shell: "swapoff -a"
  - name: disable swap in fstab
    mount:
      name: swap
      fstype: swap
      state: absent
  - name: k8s apt-key
    shell: |
      curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{k8s_repo_version}}/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg --yes
  - name: k8s repo
    apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{k8s_repo_version}}/deb/ /"
      state: present
      filename: kubernetes.list
  - name: elastic key
    shell: |
      curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch |sudo gpg --dearmor -o /etc/apt/keyrings/elastic-apt-keyring.gpg --yes
  - name: elastic repo
    apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/elastic-apt-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
      state: present
      filename: elastic-8.x.list
  - name: Wait for apt lock to be released
    ansible.builtin.command: while sudo lsof /var/lib/dpkg/lock 2> /dev/null; do sleep 10; done
    args:
      creates: /var/lib/dpkg/lock # Only runs if lock file exists (simple check)
    become: true

  - name: apt update
    apt:
      force_apt_get: 'yes'
      update_cache: 'yes'
      upgrade: 'yes'
  - name: k8s dependencies
    apt:
      allow_change_held_packages: true
      allow_downgrade: true
      pkg:
      - apt-transport-https
      - ca-certificates
      - parted
      - kubelet
      - kubectl
      - kubeadm
      - containerd
      - open-iscsi
      - ceph-common
      - clang
      - metricbeat
  - name: hold k8s
    dpkg_selections:
      name: "{{ item }}"
      selection: hold
    with_items:
    - kubelet
    - kubeadm
    - kubectl
  - name: enable containerd
    ansible.builtin.systemd:
      name: containerd.service
      state: started
      enabled: true
      daemon_reload: true
  - name: enable metricbeat
    ansible.builtin.systemd:
      name: metricbeat.service
      state: started
      enabled: true
      daemon_reload: true

      

