- hosts: localhost
  gather_facts: no
  environment:
    KUBECONFIG: "{{ kubeconf | default('/Users/ysung/.kube/config')}}"
  tasks:
  - name: create rook-ceph namespace
    kubernetes.core.k8s:
      name: rook-ceph
      api_version: v1
      kind: Namespace
      state: present
  - name: rook-ceph crd
    kubernetes.core.k8s:
      state: present
      src: "{{ item }}"
    tags: upgrade
    with_items:
      - ~/git/rook/deploy/examples/crds.yaml
      - ~/git/rook/deploy/examples/common.yaml
      - ~/git/rook/deploy/examples/csi-operator.yaml
      - ~/git/rook/deploy/examples/operator.yaml
  - name: wait for ...
    ansible.builtin.wait_for:
      timeout: 30
  - name: rook-ceph cluster
    kubernetes.core.k8s:
      state: present
      src: ~/git/rook/deploy/examples/cluster.yaml
  #- name: wait for ...
  #  ansible.builtin.wait_for:
  #    timeout: 30
  #- name: rook-ceph block storage
  #  kubernetes.core.k8s:
  #    state: present
  #    src: ~/git/rook/deploy/examples/csi/rbd/storageclass.yaml 
  #- name: wait for ...
  #  ansible.builtin.wait_for:
  #    timeout: 30
  #- name: set default storage class
  #  ansible.builtin.shell: |
  #    kubectl patch storageclass rook-ceph-block -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
  # - name: rook-ceph toolbox
  #   kubernetes.core.k8s:
  #     state: present
  #     src: ~/git/rook/deploy/examples//toolbox.yaml
